//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFramework.Infrastructure.Transversal.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IFramework.Infrastructure.Transversal.Resources.Languages.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu {0} {1} için zaten atanmış durumdadır..
        /// </summary>
        public static string AlreadyAssigned {
            get {
                return ResourceManager.GetString("AlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinmek istenen {0} bulunamadı. Zaten silinmiş veya hiç kayıt edilmemiş olabilir..
        /// </summary>
        public static string AlreadyDeletedException {
            get {
                return ResourceManager.GetString("AlreadyDeletedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatalı email doğrulama kodu girilmiştir..
        /// </summary>
        public static string EmailApprovedCodeException {
            get {
                return ResourceManager.GetString("EmailApprovedCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının email adresi doğrulanmadı. Email adresini doğruladıktan sonra giriş yapabilir..
        /// </summary>
        public static string EmailIsNotApproved {
            get {
                return ResourceManager.GetString("EmailIsNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi kayıtlı değildir..
        /// </summary>
        public static string EmailNotRegistered {
            get {
                return ResourceManager.GetString("EmailNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email adresi sistemde kullanılmaktadır..
        /// </summary>
        public static string EmailRegisteredAlready {
            get {
                return ResourceManager.GetString("EmailRegisteredAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parametresi boş olamaz..
        /// </summary>
        public static string EmptyParameterException {
            get {
                return ResourceManager.GetString("EmptyParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email veya şifre yanlış girilmiştir..
        /// </summary>
        public static string FailedLogin {
            get {
                return ResourceManager.GetString("FailedLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetki tipi yanlış belirtildi..
        /// </summary>
        public static string InvalidAuthorizationType {
            get {
                return ResourceManager.GetString("InvalidAuthorizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz {0}, Lütfen geçerli bir {1} gönderiniz..
        /// </summary>
        public static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz şifre gönderildi..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının uzun süre işlem yapmamasından dolayı tekrar giriş yapması gerekmektedir..
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönderilen kullanıcı id&apos;si ve token içerisindeki kullanıcı id&apos;si eşleşmemektedir..
        /// </summary>
        public static string IsNotMatchTokenUserIdAndRequestUserId {
            get {
                return ResourceManager.GetString("IsNotMatchTokenUserIdAndRequestUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem yapılacak nesne bulunamadı..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parametresi null olamaz..
        /// </summary>
        public static string NullParameterException {
            get {
                return ResourceManager.GetString("NullParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli istek gönderilmedi. Token kontrol edilmelidir..
        /// </summary>
        public static string NullTokenException {
            get {
                return ResourceManager.GetString("NullTokenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} aynı olmalıdır..
        /// </summary>
        public static string ParameterNotApproval {
            get {
                return ResourceManager.GetString("ParameterNotApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni şifreniz eski şifreniz ile aynı olamaz..
        /// </summary>
        public static string SamePasswordException {
            get {
                return ResourceManager.GetString("SamePasswordException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} karakterden uzun olamaz..
        /// </summary>
        public static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} karakterden kısa olamaz..
        /// </summary>
        public static string StringTooShort {
            get {
                return ResourceManager.GetString("StringTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının bu işlem için yetkisi bulunmamaktadır.
        /// </summary>
        public static string UnAuthorizedTransaction {
            get {
                return ResourceManager.GetString("UnAuthorizedTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellemek istediğiniz kullanıcıya ait kullanıcı bilgileri bulunmamaktadır. Bu kullanıcı için yeni kullanıcı bilgileri oluşturmayı deneyiniz..
        /// </summary>
        public static string UserInfoNotRegistered {
            get {
                return ResourceManager.GetString("UserInfoNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bulunamadı..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
